name: CI

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.9"
            mpi: ""
            doctest: true

          - os: macos-latest
            python-version: "3.8"
            mpi: "mpich"

    env:
      MPICH_INTERFACE_HOSTNAME: localhost
      USE_MPI: ${{ matrix.mpi }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        if: mpi != ""
        with:
          mpi: ${{ matrix.mpi }}

      - name: Pip install packages
        if: ${{ ! matrix.oldest_deps }}
        run: |
          pip install netket[dev] 
          if [ -z "${{ matrix.mpi }}" ]; then
            pip install -e 'netket[dev]' 'jax[cpu]'
          else
            pip install -e 'netket[dev,mpi]' 'jax[cpu]'
          fi

      - name: Run tests
        run: |
          export NETKET_EXPERIMENTAL=1
          pytest --cov=netket --cov-append test

      - name: NetKet docstring tests
        if: ${{ matrix.doctest }}
        run: |
          pytest --doctest-continue-on-failure --doctest-modules netket/

      - name: MPI tests
        if: matrix.mpi != ''
        run: |
          mpirun -host localhost:2 -np 2 coverage run -m pytest -n 0 test
          coverage combine --append

      - name: Upload coverage
        uses: codecov/codecov-action@v1